[package]
name = "causal_ts"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
api_version = { path = "../api_version" }
collections = { path = "../collections" }
engine_rocks = { path = "../engine_rocks", default-features = false }
engine_traits = { path = "../engine_traits", default-features = false }
error_code = { path = "../error_code", default-features = false }
fail = "0.4"
futures = { version = "0.3", features = ["thread-pool", "compat"] }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
parking_lot = "0.12"
pd_client = { path = "../pd_client", default-features = false }
raftstore = { path = "../raftstore", default-features = false }
raft = { version = "0.7.0", default-features = false, features = ["protobuf-codec"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tempfile = "3.0"
thiserror = "1.0"
tikv_util = { path = "../tikv_util", default-features = false }
txn_types = { path = "../txn_types", default-features = false }

[dev-dependencies]
test_raftstore = { path = "../test_raftstore", default-features = false }
test_util = { path = "../test_util", default-features = false }

[[test]]
name = "integrations"
path = "tests/integrations/mod.rs"
